//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhygitalTool.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesFlow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFlow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhygitalTool.Web.Resources.ResourcesFlow", typeof(ResourcesFlow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar de home pagina.
        /// </summary>
        internal static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duid 1 of meerdere antwoorden aan.
        /// </summary>
        internal static string ChoseMulptiple {
            get {
                return ResourceManager.GetString("ChoseMulptiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies 1 van de opties.
        /// </summary>
        internal static string ChoseOne {
            get {
                return ResourceManager.GetString("ChoseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einde van de Cirulaire flow.
        /// </summary>
        internal static string EndCirculair {
            get {
                return ResourceManager.GetString("EndCirculair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einde van de lineare flow.
        /// </summary>
        internal static string EndLinear {
            get {
                return ResourceManager.GetString("EndLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intresse?.
        /// </summary>
        internal static string InterestHeading {
            get {
                return ResourceManager.GetString("InterestHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laat hier je gegevens achter..
        /// </summary>
        internal static string IntrestDescription {
            get {
                return ResourceManager.GetString("IntrestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan de QR code om je contactgegevens achter te laten.
        /// </summary>
        internal static string ScanCode {
            get {
                return ResourceManager.GetString("ScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Circular flow.
        /// </summary>
        internal static string StartCirculair {
            get {
                return ResourceManager.GetString("StartCirculair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
    }
}
